# docker-compose.yml
version: '3'
services:
  scraper_server:
    build:
      context: .
      dockerfile: Dockerfile
    command: python server.py
    ports:
      - "27500:27500"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"